version: '2.0'
services:
  api:
    build: api
    restart: on-failure
    ports:
    - "8081:8081"
  # apk-build:
  #   build: app
  # web:
  #   build: web
  #   restart: on-failure
  #   ports:
  #     - "8080:8080"
